s3:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/scality/s3server:mem-latest"
  ports:
    - "33333:8000"
sqs:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/s12v/elasticmq"
  ports:
    - "9324:9324"
wiremock:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/rodolpheche/wiremock"
  ports:
    - "8080:8080"
  volumes:
    - "${ROOT}/sierra_adapter/sierra_reader/src/test/resources/wiremock:/home/wiremock"
