sqs:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/s12v/elasticmq"
  ports:
    - "9324:9324"
mysql:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/library/mysql:5.6"
  ports:
    - "3307:3306"
  environment:
    - "MYSQL_ROOT_PASSWORD=password"
s3:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/scality/s3server:mem-latest"
  ports:
    - "33333:8000"
