sqs:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/s12v/elasticmq"
  ports:
    - "9324:9324"
s3:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/scality/s3server:mem-latest"
  ports:
    - "33333:8000"
dynamodb:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/peopleperhour/dynamodb"
  ports:
    - "45678:8000"
