sqs:
  image: s12v/elasticmq
  ports:
    - "9324:9324"

inferrer:
  image: feature_inferrer
  ports:
    - "3141:80"
  environment:
    MODEL_OBJECT_KEY: test-model.pkl
  volumes:
    - ../test_data:/app/data
  links:
    - "image_server:image_server"

image_server:
  image: nginx
  expose:
    - "80"
  volumes:
    - ../test_data:/usr/share/nginx/html:ro
