sqs:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/s12v/elasticmq"
  ports:
    - "9324:9324"
sts:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/localstack/localstack:0.10.5"
  ports:
    - "4592:4592"
    - "4572:4572"
  environment:
    - SERVICES=sts,s3
s3:
  image: "760097843905.dkr.ecr.eu-west-1.amazonaws.com/scality/s3server:mem-latest"
  ports:
    - "33333:8000"
